services:
  - type: web
    name: adevafrica-web
    env: ruby
    buildCommand: bundle install && yarn install && bundle exec rails assets:precompile
    startCommand: bundle exec rails server -p $PORT -e $RAILS_ENV
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RAILS_SERVE_STATIC_FILES
        value: true
      - key: RAILS_LOG_TO_STDOUT
        value: true
      - key: DATABASE_URL
        fromDatabase:
          name: adevafrica-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: adevafrica-redis
          property: connectionString
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: MAPBOX_API_KEY
        sync: false
      - key: ASSISTANT_API_KEY
        sync: false

  - type: worker
    name: adevafrica-worker
    env: ruby
    buildCommand: bundle install
    startCommand: bundle exec sidekiq -C config/sidekiq.yml
    envVars:
      - key: RAILS_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: adevafrica-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: adevafrica-redis
          property: connectionString
      - key: SECRET_KEY_BASE
        generateValue: true

databases:
  - name: adevafrica-db
    databaseName: adevafrica_production
    user: adevafrica

services:
  - type: redis
    name: adevafrica-redis
    ipAllowList: []

